#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

mkdir -p assets/fonts

# Google Fonts self-hosted WOFF2 (latin subset)
# Note: these URLs are generated by fonts.googleapis.com for the requested families/weights.
echo "Vendoring fonts (Montserrat, Questrial)"
curl -fsSL "https://fonts.gstatic.com/s/montserrat/v31/JTUSjIg1_i6t8kCHKm459WlhyyTh89Y.woff2" \
  -o assets/fonts/montserrat-latin.woff2
curl -fsSL "https://fonts.gstatic.com/s/questrial/v19/QdVUSTchPBm7nuUeVf70viFluW44JQ.woff2" \
  -o assets/fonts/questrial-latin.woff2

echo "Done."
echo "  assets/fonts/montserrat-latin.woff2"
echo "  assets/fonts/questrial-latin.woff2"
